# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Libary.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(550, 390)
        Main.setFixedSize(550, 390)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 531, 44))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.SearchGroup = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.SearchGroup.setContentsMargins(0, 0, 0, 0)
        self.SearchGroup.setObjectName("SearchGroup")
        self.SearchEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.SearchEdit.setText("")
        self.SearchEdit.setObjectName("SearchEdit")
        self.SearchGroup.addWidget(self.SearchEdit, 1, 0, 1, 1)
        self.SearchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchGroup.addWidget(self.SearchButton, 1, 1, 1, 1)
        self.SearchLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.SearchLabel.setObjectName("SearchLabel")
        self.SearchGroup.addWidget(self.SearchLabel, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Main)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 531, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.AddGroup = QtWidgets.QGridLayout(self.horizontalLayoutWidget_2)
        self.AddGroup.setContentsMargins(0, 0, 0, 0)
        self.AddGroup.setObjectName("AddGroup")
        self.GenreEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.GenreEdit.setText("")
        self.GenreEdit.setObjectName("GenreEdit")
        self.AddGroup.addWidget(self.GenreEdit, 1, 2, 1, 1)
        self.NameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.NameEdit.setText("")
        self.NameEdit.setObjectName("NameEdit")
        self.AddGroup.addWidget(self.NameEdit, 1, 0, 1, 1)
        self.DateEdit = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.DateEdit.setObjectName("DateEdit")
        self.AddGroup.addWidget(self.DateEdit, 1, 3, 1, 1)
        self.AuthorEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.AuthorEdit.setText("")
        self.AuthorEdit.setObjectName("AuthorEdit")
        self.AddGroup.addWidget(self.AuthorEdit, 1, 1, 1, 1)
        self.AddLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.AddLabel.setObjectName("AddLabel")
        self.AddGroup.addWidget(self.AddLabel, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Main)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Main)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 531, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.BooksGroup = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.BooksGroup.setContentsMargins(0, 0, 0, 0)
        self.BooksGroup.setObjectName("BooksGroup")
        self.BookLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.BookLabel.setObjectName("BookLabel")
        self.BooksGroup.addWidget(self.BookLabel, 1, 0, 1, 1)
        self.BookTable = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.BookTable.setObjectName("BookTable")
        self.BookTable.setColumnCount(5)
        self.BookTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BookTable.setHorizontalHeaderItem(0, item)
        self.BookTable.setColumnWidth(0, 65)
        item = QtWidgets.QTableWidgetItem()
        self.BookTable.setHorizontalHeaderItem(1, item)
        self.BookTable.setColumnWidth(1, 150)
        item = QtWidgets.QTableWidgetItem()
        self.BookTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BookTable.setHorizontalHeaderItem(4, item)
        self.BookTable.setColumnWidth(4, 110)
        self.BooksGroup.addWidget(self.BookTable, 2, 0, 1, 1)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "БД Библиотека"))
        self.SearchEdit.setPlaceholderText(_translate("Main", "Введите название книги"))
        self.SearchButton.setText(_translate("Main", "Поиск"))
        self.SearchLabel.setText(_translate("Main", "Поиск книг:"))
        self.GenreEdit.setPlaceholderText(_translate("Main", "Введите жанр книги"))
        self.NameEdit.setPlaceholderText(_translate("Main", "Введите название книги"))
        self.AuthorEdit.setPlaceholderText(_translate("Main", "Введите имя автора"))
        self.AddLabel.setText(_translate("Main", "Добавление книги в базу данных:"))
        self.label_4.setText(_translate("Main", "БИБЛИОТЕКА"))
        self.BookLabel.setText(_translate("Main", "Имеющиеся книги в базе данных:"))
        item = self.BookTable.horizontalHeaderItem(0)
        item.setText(_translate("Main", "№ книги"))
        item = self.BookTable.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Название книги"))
        item = self.BookTable.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Автор книги"))
        item = self.BookTable.horizontalHeaderItem(3)
        item.setText(_translate("Main", "Жанр книги"))
        item = self.BookTable.horizontalHeaderItem(4)
        item.setText(_translate("Main", "Дата публикации"))

class LibraryApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Main()
        self.ui.setupUi(self)


def main():
    app = QApplication(sys.argv)
    window = LibraryApp()
    window.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()